name: Build and Deploy Angular

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular for GitHub Pages
        run: |
          npm run build -- --configuration=production --base-href "/AutomataLab/"
          cp dist/AutomataLab/browser/index.html dist/AutomataLab/browser/404.html

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/AutomataLab/browser
          publish_branch: gh-pages
          commit_message: "Deploy from GitHub Actions [skip ci]"