name: Build and Deploy Angular

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci


      - name: Build Angular
        run: npm run build -- --configuration=production

      - name: Add 404.html redirect for SPA
        run: cp dist/AutomataLab/browser/index.html dist/AutomataLab/browser/404.html

      - name: Deploy to deploy branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          if git show-ref --quiet refs/heads/deploy; then
            git checkout deploy
          else
            git checkout --orphan deploy
          fi

          git rm -rf . || true

          cp -r dist/AutomataLab/browser/* .

          git add .

          git commit -m "Deploy from GitHub Actions [skip ci]" || echo "No changes to commit"

          git push origin deploy --force
